/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab13;

import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author as063
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTemp = new javax.swing.ButtonGroup();
        javax.swing.JPanel panelTempUnits = new javax.swing.JPanel();
        javax.swing.JPanel panelTempSelector = new javax.swing.JPanel();
        sliderTemp = new javax.swing.JSlider();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel panelTempRange = new javax.swing.JPanel();
        textMinTemp = new javax.swing.JTextField();
        lblCurTemp = new javax.swing.JLabel();
        textMaxTemp = new javax.swing.JTextField();
        rdbtnFahTemp = new javax.swing.JRadioButton();
        rdbtnCelTemp = new javax.swing.JRadioButton();
        panelTempKevin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textTempKelvin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelvin Converter");
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        panelTempUnits.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Temperature"), "Temperature"));
        panelTempUnits.setLayout(new java.awt.GridLayout(0, 1));

        panelTempSelector.setLayout(new java.awt.GridLayout(0, 1));
        panelTempSelector.add(sliderTemp);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Use the slider to<br/>adjust the temperature</html>");
        jLabel1.setToolTipText("");
        panelTempSelector.add(jLabel1);

        textMinTemp.setColumns(5);
        textMinTemp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        panelTempRange.add(textMinTemp);

        lblCurTemp.setText("0.0");
        panelTempRange.add(lblCurTemp);

        textMaxTemp.setColumns(5);
        textMaxTemp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textMaxTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaxTempActionPerformed(evt);
            }
        });
        panelTempRange.add(textMaxTemp);

        panelTempSelector.add(panelTempRange);

        panelTempUnits.add(panelTempSelector);

        buttonGroupTemp.add(rdbtnFahTemp);
        rdbtnFahTemp.setText("Fahrenheit");
        panelTempUnits.add(rdbtnFahTemp);

        buttonGroupTemp.add(rdbtnCelTemp);
        rdbtnCelTemp.setText("Celcius");
        rdbtnCelTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCelTempActionPerformed(evt);
            }
        });
        panelTempUnits.add(rdbtnCelTemp);

        jLabel3.setText("Temperature in Kelvin: ");
        panelTempKevin.add(jLabel3);

        textTempKelvin.setEditable(false);
        textTempKelvin.setBackground(java.awt.Color.black);
        textTempKelvin.setColumns(10);
        textTempKelvin.setForeground(java.awt.Color.cyan);
        textTempKelvin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelTempKevin.add(textTempKelvin);

        panelTempUnits.add(panelTempKevin);

        getContentPane().add(panelTempUnits, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnCelTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnCelTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnCelTempActionPerformed

    private void textMaxTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaxTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaxTempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              //  if ("Nimbus".equals(info.getName())) {
                //    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  //  break;
                //}
           //
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    public JRadioButton getRdbtnCelTemp() {
        return rdbtnCelTemp;
    }

    public JRadioButton getRdbtnFahTemp() {
        return rdbtnFahTemp;
    }

    public JSlider getSliderTemp() {
        return sliderTemp;
    }

    public JTextField getTextTempKelvin() {
        return textTempKelvin;
    }

    public JLabel getLblCurTemp() {
        return lblCurTemp;
    }

    public JTextField getTextMaxTemp() {
        return textMaxTemp;
    }

    public JTextField getTextMinTemp() {
        return textMinTemp;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTemp;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCurTemp;
    private javax.swing.JPanel panelTempKevin;
    private javax.swing.JRadioButton rdbtnCelTemp;
    private javax.swing.JRadioButton rdbtnFahTemp;
    private javax.swing.JSlider sliderTemp;
    private javax.swing.JTextField textMaxTemp;
    private javax.swing.JTextField textMinTemp;
    private javax.swing.JTextField textTempKelvin;
    // End of variables declaration//GEN-END:variables
}
